Revert "integration: move to Python3 (#4313)" (#4323)
This reverts commit 561bd01456e91f7813d4ec946f316366fd7a3cf5.

People's tests have been breaking on `docker-compose up` with the following output:

```
ImportError: No module named requests
```

Fixes #4322